# Generated by Django 4.0.1 on 2022-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
             name='Services',
             fields=[
                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('email', models.CharField(max_length=122)),
                 ('passward', models.CharField(max_length=122)),
                 ('repeat_passward', models.CharField(max_length=122)),
            ],
        ),
    ]
