# Generated by Django 4.0.1 on 2022-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tabletname', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField(max_length=50)),
                ('Product_description', models.TextField()),
                ('Expiry_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
