# Generated by Django 4.0.1 on 2022-01-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_donor_donor1'),
    ]

    operations = [
        migrations.CreateModel(
            name='reciever1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet', models.CharField(max_length=20)),
                ('Required_Qty', models.IntegerField(max_length=50)),
                ('Prescribed_by', models.CharField(max_length=20)),
            ],
        ),
    ]
