# Generated by Django 4.0.1 on 2022-01-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reciever1'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('psw', models.CharField(max_length=20)),
                ('psw_repeat', models.CharField(max_length=20)),
            ],
        ),
    ]
