# Generated by Django 4.0.1 on 2022-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_signup1'),
    ]

    operations = [
        migrations.CreateModel(
            name='login1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Psw', models.CharField(max_length=20)),
            ],
        ),
    ]
